### ISSUE TITLE
S3 storage backend

### ISSUE THREAD

**Issue by nullobject** [rubygems/gemstash#143]
Hi there, I'm keen to write an S3 storage backend. That way a gemstash server could be easily deployed to providers like Heroku, etc.

Given there is no plugin system (yet), is this just a matter of providing my own S3 `Storage` and `Resource` classes?

**Comment by hmistry** [comment]
@nullobject That's great to hear. We'd love to have you contribute on that feature. Before diving into the implementation, it would help us a lot if we had an idea of what you're intending to implement, how it will fit in and address the needs of you and others.

First step, I see there's a discussion in issue #107. It would be great if you could start by putting together an [RFC here](https://github.com/bundler/rfcs). That way we can collect feedback from everyone and potentially save you from doing all this work that may not get merged because it doesn't meet the needs.

**Comment by duyquangnguyenhac** [comment]
Hi everyone, is this issue still up for grabs? I'm intending to work on a backend cloud storage compatibility for gemstash for GSOC. So far, gemstash seems to serve as a proxy for bundler API which utilizes an internet connection with rubygems.org. I’m interested in further developing the offline functions of gemstash as a local, independent gem source. I think implementing different cloud storage services such as Amazon S3, Google Cloud Platform, or Microsoft Azure could greatly improve Gemstash’s capabilities. Implementing the option to use multiple gem storages (per gem, or group) is also something I would like to achieve in the long run. There will be more work to do, and I'll proceed to come up with a detailed proposal of what I'm intending to implement soon, just getting the idea out there!
- thank you, James

**Comment by bronzdoc** [comment]
It is @duyquangnguyenhac! thanks!

**Comment by bronzdoc** [comment]
Closed by https://github.com/rubygems/gemstash/pull/270
