### ISSUE TITLE
Special case to replace existing gems

### ISSUE THREAD

**Issue by micheelengronne** [rubygems/gemstash#266]
I know that yank does not permit to upload a gem with the same version again.

There is a use case where this behaviour is necessary.

Let's image that you use your private gemstash to upload fat gems (gems with native extensions).

You do not necessarily have control over the code of the source gems of these fat gems.

If you do a mistake and upload a fat gem with the wrong compilation flag for instance, you have a problem. You canno't upload another gem with the same version and you canno't upload a gem with a new version (you don't have control over the versions, remember).

What can you do in that case ?

I think there should be an option that authorizes reupload of gems in private gemstashes for this specific case.

**Comment by indirect** [comment]
The traditional way to handle this, on rubygems.org, is to add yet another version number. For example, Nokogiri 1.6.6.1 - 1.6.6.4. IIRC the source code didn't change from version 1.6.4, but the native compilations did.

Is there a reason that option doesn't work for you?

**Comment by micheelengronne** [comment]
That option could work but if I increase my version without the upstream (source code) knowing it that can raise future conflicts if the upstream increase its version too and end up having the same than me.

**Comment by micheelengronne** [comment]
BTW, that's intuitively what I thought, to use the 4th number in the version. But if the upstream (source code) does the same ?

**Comment by indirect** [comment]
If the upstream uses a 4th version number and you need to release multiple versions of that gem, you can use a 5th version number to track your changes.

It makes sense that you want the ability to upload over yanked versions. To be perfectly honest, the Gemstash team is unlikely to add support for this into Gemstash directly because it conflicts with a core value of RubyGems: gem content never changes once it has been assigned a version number.

That said, you can always modify the database contents directly or modify your local copy of Gemstash temporarily if you really, really desperately need to do this.

Thanks for telling us about your use case, we really appreciate the feedback.
