### ISSUE TITLE
Drop --daemonize which is not supported by stock Puma

### ISSUE THREAD

**Issue by olleolleolle** [rubygems/gemstash#359]
Perhaps it is time for this project not to default to "daemonize on". EDIT: time to remove this command-line option which is unsupported.

Puma 5 stopped daemonize by default.

Context:
https://github.com/kigster/puma-daemon#why-was-it-removed-from-puma-v5

**Comment by indirect** [comment]
I buy that argument, and I would be happy with at least defaulting to off. Honestly it's probably fine to remove entirely, as long as we bump the major version. :)

**Comment by olleolleolle** [comment]
Speculation: people perhaps run this as a Docker container anyway?

**Comment by thiagopintodev** [comment]
@indirect @olleolleolle Thank you for the work you've been doing keeping this project updated.

A fresh install of gemstash 2.6.0 on Ruby 3.2 is not running because of this.

![image](https://github.com/rubygems/gemstash/assets/335238/a4b137ba-cede-4608-9b85-d0345ad7f09e)

I would very much agree with removing it altogether, but maybe we can leave a message there instead.

I wrote a fix to raise an error while also providing some context and recommendations.

Thank you.
