### ISSUE TITLE
private gems not found unless `gem search` has --source flag

### ISSUE THREAD

**Issue by chriseckhardt** [rubygems/gemstash#78]
My setup:
Late 2013 Macbook Pro 15-inch retina OS X 10.11.3
Ruby 2.3.0p0 (via RVM 1.26.11)
gem version 2.5.1

When I spin up a gemstash instance locally and push private gems, I am unable to find them in a `gem search` without appending the `--source http://127.0.0.1/private` to my command line invocation, regardless if I've set the gemstash as my `gem source` or not.

Steps to reproduce:

```
$ gem install gemstash
$ gemstash authorize # add key to ~/.gem/credentials
$ gemstash start
$ gem push --key gemstash --host http://127.0.0.1:9292/private my_private_gem-1.2.3.gem
$ gem source -r https://rubygems.org/
$ gem source -a http://127.0.0.1:9292/private
$ gem search -ar my_private_gem

*** REMOTE GEMS ***

$ gem search -ar my_private_gem --source http://127.0.0.1:9292/private

*** REMOTE GEMS ***
my_private_gem (1.2.3)
```

**Comment by chriseckhardt** [comment]
So, it looks like I get the expected behavior if I remember to add my private gemstash as a `gem source` _with the trailing slash_

Works:

```
gem source -a http://127.0.0.1:9292/private/
```

Weird:

```
gem source -a http://127.0.0.1:9292/private
```

**Comment by smellsblue** [comment]
@chriseckhardt Sorry for the super late response, but I finally did a bit of investigating on this. Unfortunately, there's not much we can do to fix it :cry:

Rubygems is sending us requests for `/specs.4.8.gz` instead of `/prviate/specs.4.8.gz`.

I did some further digging, and traced it down to here: https://github.com/rubygems/rubygems/blob/2198729b3c4ea0f1324dfa8981db08b742af1bcc/lib/rubygems/source.rb#L184-L187

Specifically, appending `"specs.4.8.gz"` to a `URI` object. I replicated the problem in an IRB session:
```
$ irb
2.2.2 :001 > require "uri"
 => true 
2.2.2 :002 > no_slash_uri = URI.parse("http://127.0.0.1:9292/private")
 => #<URI::HTTP http://127.0.0.1:9292/private> 
2.2.2 :003 > slash_uri = URI.parse("http://127.0.0.1:9292/private/")
 => #<URI::HTTP http://127.0.0.1:9292/private/> 
2.2.2 :004 > no_slash_uri + "specs.4.8.gz"
 => #<URI::HTTP http://127.0.0.1:9292/specs.4.8.gz> 
2.2.2 :005 > slash_uri + "specs.4.8.gz"
 => #<URI::HTTP http://127.0.0.1:9292/private/specs.4.8.gz>
```

As you can see, the `/private` gets lost when the trailing slash is missing, which would explain the exact behavior you are seeing.

Meanwhile, specifying the source via `--source` works, because Rubygems specifically adds a trailing slash when missing for this case: https://github.com/rubygems/rubygems/blob/2198729b3c4ea0f1324dfa8981db08b742af1bcc/lib/rubygems/local_remote_options.rb#L107

It seems reasonable to me that if the `--source` option adds a trailing slash, then adding a source via `gem source -a` should do the same... but regardless, at that point it seems to be a Rubygems issue to me.

**Comment by bronzdoc** [comment]
Closing this since it has been stale for to long. If this is still an issue for you @chriseckhardt I'm happy to reopen, thanks
